In [1]:
import requests

                                             *** NIVEL 1 ***

1.1- Consulta la API pública JSONPlaceholder utilizando el método GET.

In [ ]:
url_posts = "https://jsonplaceholder.typicode.com/posts"        # Se guarda en una variable para si cambia la URL solo modificar 1 línea
respuesta_posts = requests.get(url_posts)                 # Petición HTTP
posts = respuesta_posts.json()                   # El método .json() convierte ese JSON en objetos de Python.
posts[0]

{'userId': 1,
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [4]:
url_users = "https://jsonplaceholder.typicode.com/users"

respuesta_users = requests.get(url_users)

users = respuesta_users.json()

users[0]

{'id': 1,
 'name': 'Leanne Graham',
 'username': 'Bret',
 'email': 'Sincere@april.biz',
 'address': {'street': 'Kulas Light',
  'suite': 'Apt. 556',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
 'phone': '1-770-736-8031 x56442',
 'website': 'hildegard.org',
 'company': {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'}}

In [5]:
url_todos = "https://jsonplaceholder.typicode.com/todos"

respuesta_todos = requests.get(url_todos)

todos = respuesta_todos.json()

todos[0]

{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}

1.2- Muestra por pantalla:

In [ ]:
# Cantidad de recursos
print("Número de publicaciones:", len(posts))     # posts, users y todos son listas, podemos utilizar la función len() para saber cuántos elementos contienen.
print("Número de usuarios:", len(users))
print("Número de tareas:", len(todos))

Número de publicaciones: 100
Número de usuarios: 10
Número de tareas: 200

In [7]:
# Código de estado
print("Código de estado de publicaciones:", respuesta_posts.status_code)
print("Código de estado de usuarios:", respuesta_users.status_code)
print("Código de estado de tareas:", respuesta_todos.status_code)

Código de estado de publicaciones: 200
Código de estado de usuarios: 200
Código de estado de tareas: 200

1.3- 3. Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [ ]:
url_post_inexistente = "https://jsonplaceholder.typicode.com/posts/991"

respuesta_404 = requests.get(url_post_inexistente)

print("Código de estado:", respuesta_404.status_code)   # Porque el servidor recibe una petición válida (GET), pero el recurso solicitado (/posts/991) no existe

Código de estado: 404

1.4- Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.
Muestra la respuesta JSON.
Muestra el código de estado.

In [ ]:
url_posts = "https://jsonplaceholder.typicode.com/posts"

nueva_publicacion = {                                            # Los datos se crean como un diccionario de Python.
    "title": "Mi primera publicación",
    "body": "Esta publicación ha sido creada desde Python utilizando requests.",
    "userId": 1
}

respuesta_post = requests.post(url_posts, json=nueva_publicacion)    # indica a qué recurso enviamos la petición y convierte el diccionario a JSON y lo envía en el cuerpo (body) de la petición.

print("Respuesta JSON:")
print(respuesta_post.json())

print()

print("Código de estado:", respuesta_post.status_code)    # Devuelve 201 Created (EL recurso se ha creado correctamente)

Respuesta JSON:
{'title': 'Mi primera publicación', 'body': 'Esta publicación ha sido creada desde Python utilizando requests.', 'userId': 1, 'id': 101}

Código de estado: 201

1.5- 5. Realiza una petición PATCH para modificar parcialmente una publicación existente.
Muestra la respuesta JSON.
Muestra el código de estado.

In [18]:
url_patch = "https://jsonplaceholder.typicode.com/posts/1"    # Se modifica la publicación con id = 1.

datos_actualizados = {
    "title": "Título modificado desde Python"
}

respuesta_patch = requests.patch(url_patch, json=datos_actualizados)

print("Respuesta JSON:")
print(respuesta_patch.json())

print()

print(f"Código de estado: {respuesta_patch.status_code}")   # El código 200 OK significa que el servidor ha procesado la petición con éxito y devuelve el recurso actualizado

Respuesta JSON:
{'userId': 1, 'id': 1, 'title': 'Título modificado desde Python', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Código de estado: 200

1.6- Haz una petición DELETE sobre una publicación.
Muestra la respuesta JSON.
Muestra el código de estado.

In [ ]:
url_delete = "https://jsonplaceholder.typicode.com/posts/1"

respuesta_delete = requests.delete(url_delete)        # No es necesario enviar un body, porque el recurso que queremos eliminar ya está identificado en la URL.

print("Respuesta JSON:")
print(respuesta_delete.json())

print(f"Código de estado: {respuesta_delete.status_code}")    # Devuelve 200 OK (la eliminación fue correcta y el servidor devuelve alguna información)

Respuesta JSON:
{}
Código de estado: 200

                             *** NIVEL 2 ***

**2.1** - Interacción con una API pública real

Para esta práctica se ha seleccionado la API **Open-Meteo**, disponible en el repositorio **Public APIs** de GitHub.

Esta API proporciona información meteorológica mediante peticiones HTTP GET, devuelve los datos en formato JSON y no requiere autenticación mediante API Key, por lo que resulta adecuada para trabajar con la librería `requests` de Python.

***2.2.1***- ## Endpoints disponibles

Tras revisar la documentación de Open-Meteo, se han identificado los siguientes endpoints:

- **Weather Forecast**: permite obtener la previsión meteorológica para una ubicación determinada.
- **Air Quality**: proporciona información sobre la calidad del aire y diferentes contaminantes atmosféricos.

***2.2.2***- Parámetros de la API

La API Open-Meteo permite utilizar diferentes parámetros para personalizar las consultas. Algunos de los más relevantes son:

- latitude: indica la latitud de la ubicación de la consulta.
- longitude: indica la longitud de la ubicación.
- current: permite solicitar datos meteorológicos actuales, como la temperatura o la velocidad del viento.
- hourly: permite obtener variables meteorológicas con frecuencia horaria.
- daily: permite obtener información meteorológica diaria, como la temperatura máxima y mínima.
- timezone: permite especificar la zona horaria en la que se desean recibir los datos.

***2.2.3***- Tras revisar la documentación de la API Open-Meteo, se ha comprobado que las respuestas se devuelven en formato **JSON (JavaScript Object Notation)**.

Este formato organiza la información en pares **clave-valor**, como por ejemplo 'latitude', 'longitude'', 'timezone' y 'hourly', lo que facilita el procesamiento de los datos desde Python utilizando la librería 'requests' y su posterior conversión a un DataFrame de pandas

**2.3**-  Haz una petición GET sencilla:
Muestra el código de estado de la respuesta.
Imprime de forma clara algunos de los campos de la respuesta JSON.

In [21]:
# URL de la API
url = "https://api.open-meteo.com/v1/forecast"

# Parámetros de la consulta
parametros = {
    "latitude": 41.39,
    "longitude": 2.17,
    "current": "temperature_2m"
}

# Petición GET
respuesta = requests.get(url, params=parametros)

# Código de estado
print(f"Código de estado: {respuesta.status_code}")

# Convertir la respuesta JSON a un diccionario
datos = respuesta.json()

# Mostrar algunos campos de la respuesta
print(f"Latitud: {datos['latitude']}")
print(f"Longitud: {datos['longitude']}")
print(f"Zona horaria: {datos['timezone']}")
print(f"Temperatura actual: {datos['current']['temperature_2m']} °C")

Código de estado: 200
Latitud: 41.4375
Longitud: 2.1875
Zona horaria: GMT
Temperatura actual: 22.9 °C

***2.4***  Convierte los datos a un DataFrame de pandas:

Muestra las primeras filas de DataFrame.

In [24]:
import pandas as pd

# Convertir los datos actuales en un DataFrame
df_current = pd.DataFrame([datos["current"]])

# Mostrar las primeras filas
df_current.head()

               time  interval  temperature_2m
0  2026-07-27T03:15       900            22.9

In [25]:
df = pd.DataFrame([datos])
df.head()

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,current_units,current
0,41.4375,2.1875,0.025392,0,GMT,GMT,29.0,"{'time': 'iso8601', 'interval': 'seconds', 'te...","{'time': '2026-07-27T03:15', 'interval': 900, ..."

                           *** NIVEL 3 ***

**3.1** Buscar un dataset de tu interés mediante package_search y package_show.

In [27]:
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"

parametros = {
    "q": "bicing"
}

respuesta = requests.get(url, params=parametros)

print(f"Código de estado: {respuesta.status_code}")

datos = respuesta.json()

# Mostrar el número de resultados encontrados
print(f"Número de datasets encontrados: {datos['result']['count']}")

# Mostrar el título de los primeros 5 datasets
for dataset in datos["result"]["results"][:5]:
    print(dataset["title"])

Código de estado: 200
Número de datasets encontrados: 5
New Bicing stations status of Barcelona city
New Bicing stations information of the city of Barcelona
Bicing service use of the city of Barcelona from August 2018 to March 2019
Photographic catalogue of urban features on the Open Repository of Knowledge of the City Council of Barcelona (BCNROC)
Bicing stations, mechanical and electrical, in the city of Barcelona from August 2018 to March 2019

In [ ]:
for dataset in datos["result"]["results"]:         # package_show necesita el nombre interno (name), no el título.
    print(f"Título: {dataset['title']}")
    print(f"Nombre: {dataset['name']}")
    print("-" * 50)

Título: New Bicing stations status of Barcelona city
Nombre: estat-estacions-bicing
--------------------------------------------------
Título: New Bicing stations information of the city of Barcelona
Nombre: informacio-estacions-bicing
--------------------------------------------------
Título: Bicing service use of the city of Barcelona from August 2018 to March 2019
Nombre: us-del-servei-bicing
--------------------------------------------------
Título: Photographic catalogue of urban features on the Open Repository of Knowledge of the City Council of Barcelona (BCNROC)
Nombre: cataleg-fotografies-elements-urbans-bcnroc
--------------------------------------------------
Título: Bicing stations, mechanical and electrical, in the city of Barcelona from August 2018 to March 2019
Nombre: bicing
--------------------------------------------------

In [29]:
url_show = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"

parametros = {
    "id": "estat-estacions-bicing"
}

respuesta_show = requests.get(url_show, params=parametros)

print(f"Código de estado: {respuesta_show.status_code}")

datos_show = respuesta_show.json()

Código de estado: 200

In [ ]:
print(f"Título: {datos_show['result']['title']}")        # Campos interesantes
print(f"Autor: {datos_show['result']['author']}")
print(f"Organización: {datos_show['result']['organization']['title']}")
print(f"Número de recursos: {len(datos_show['result']['resources'])}")

Título: New Bicing stations status of Barcelona city
Autor: Gerència d'Ecologia, Urbanisme i Mobilitat
Organización: Transport
Número de recursos: 87

In [ ]:
for recurso in datos_show["result"]["resources"]:         # Muestra los archivos que tiene el dataset
    print(f"Nombre: {recurso['name']}")
    print(f"Formato: {recurso['format']}")
    print(f"URL: {recurso['url']}")
    print("-" * 50)

Nombre: Estat_Estacions_Bicing_securitzat_json
Formato: JSON
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1b215493-9e63-4a12-8980-2d7e0fa19f85/download
--------------------------------------------------
Nombre: 2026_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/28627d99-7c79-4eb5-bb30-2ef5016cf85e/download
--------------------------------------------------
Nombre: 2026_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/455a4db8-21ee-44e5-989b-12284e69cb86/download
--------------------------------------------------
Nombre: 2026_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/aa833a84-e434-4139-a578-deffd73a592a/download
--------------------------------------------------
Nombre: 2026_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/6bfc88ee-66f0-4c1a-82d0-e8b268665536/download
--------------------------------------------------
Nombre: 2026_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e18c8a33-d81f-40e3-8929-09ee84c5e5ef/download
--------------------------------------------------
Nombre: 2025_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/6bfc06e2-ad96-4059-a57d-ce9334452c0f/download
--------------------------------------------------
Nombre: 2025_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/af6f7cc4-3193-4b35-8e30-38f95df921cf/download
--------------------------------------------------
Nombre: 2025_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/0e904458-8d7a-42ac-b7c2-e41627a4577c/download
--------------------------------------------------
Nombre: 2025_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/885bbac5-a0d8-425e-919a-a4a855808785/download
--------------------------------------------------
Nombre: 2025_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/c14e7b54-87c8-4ea8-aa1a-a8b5828989fe/download
--------------------------------------------------
Nombre: 2025_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1b47f8e6-db40-4835-8d65-7f4349efb8f5/download
--------------------------------------------------
Nombre: 2025_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/aba91b60-68f1-4a79-ba6b-c3ac87dc8c4e/download
--------------------------------------------------
Nombre: 2025_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/02d2975f-ce3c-4215-b1b2-eb6a2b4d019e/download
--------------------------------------------------
Nombre: 2025_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/fb3e741b-299b-487d-98b4-11a8eb0634d1/download
--------------------------------------------------
Nombre: 2025_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/efcfa487-708e-4766-aa2c-5d63451d11b2/download
--------------------------------------------------
Nombre: 2025_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/fe880433-8468-4e85-a851-31036ab86af9/download
--------------------------------------------------
Nombre: 2024_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/229fdebf-daa8-4f22-9b0c-cf03ab0279ca/download
--------------------------------------------------
Nombre: 2024_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/f482f76c-0aed-4c06-9abd-f90b3ea64d69/download
--------------------------------------------------
Nombre: 2024_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/869e5799-621d-497d-8364-1cb23b718da2/download
--------------------------------------------------
Nombre: 2024_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/03816585-7818-41ca-bc18-fdf56f839fb6/download
--------------------------------------------------
Nombre: 2024_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/f8d0e63f-1c89-4bfc-bfe2-c180bdfbba70/download
--------------------------------------------------
Nombre: 2024_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e69daa68-0096-43e8-8e69-8219b9a13a4c/download
--------------------------------------------------
Nombre: 2024_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/dc17e68c-6faf-4210-b93c-864e993e9d70/download
--------------------------------------------------
Nombre: 2024_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/f0043c1f-38db-4e34-aaf8-8cd71174613b/download
--------------------------------------------------
Nombre: 2024_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/727dbd48-9348-4f43-a672-b79f73f1f8af/download
--------------------------------------------------
Nombre: 2024_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e5ed1e52-b205-49ff-b99c-a2307a8ce9a3/download
--------------------------------------------------
Nombre: 2024_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/dec7d860-dcb9-46ac-b241-4d7e711c39d6/download
--------------------------------------------------
Nombre: 2024_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/29b46066-dc16-422d-85dd-6799baa7e839/download
--------------------------------------------------
Nombre: 2023_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1ba8d8c4-c13b-47a8-b08f-19eba4266efc/download
--------------------------------------------------
Nombre: 2023_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/84c0d6e5-9011-40c2-80a7-65d9af4f671f/download
--------------------------------------------------
Nombre: 2023_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/baba6358-6554-4629-877d-a82fd3925ed7/download
--------------------------------------------------
Nombre: 2023_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/5f8d4611-6125-4ce3-82fd-39c83f0e74bb/download
--------------------------------------------------
Nombre: 2023_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/829cce55-a081-48bf-9744-c61ea26073cc/download
--------------------------------------------------
Nombre: 2023_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/f6bc68df-88a0-4e69-b513-dbbd941eea17/download
--------------------------------------------------
Nombre: 2023_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/4e75cb2a-7b6d-4f73-8ce6-be52de54d46c/download
--------------------------------------------------
Nombre: 2023_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e883bca2-d274-4eb5-8830-d75b080d34b3/download
--------------------------------------------------
Nombre: 2023_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/600f1b07-4af2-4fbb-b6d0-a473e3426d24/download
--------------------------------------------------
Nombre: 2023_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/d41a1b34-503a-4e32-afc9-1850f74a2e3b/download
--------------------------------------------------
Nombre: 2023_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/813ab563-358b-4dd5-b41c-816bf3927763/download
--------------------------------------------------
Nombre: 2023_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/42e1d85c-86e3-4122-b1b3-de0f7fcf01fa/download
--------------------------------------------------
Nombre: 2022_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e13eda87-14c3-4589-9ff9-d721c3fa4dbb/download
--------------------------------------------------
Nombre: 2022_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/2e423344-cc5b-4c96-95e4-3f47bf29f089/download
--------------------------------------------------
Nombre: 2022_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/f2b7e984-bb83-495d-b103-6e67631eb837/download
--------------------------------------------------
Nombre: 2022_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/72f96ab8-f8ae-46d8-8f4d-85220daff9fa/download
--------------------------------------------------
Nombre: 2022_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/c35e536e-256d-4ab4-afe0-62e9034f5159/download
--------------------------------------------------
Nombre: 2022_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/697dbea2-eee2-4679-9dc4-100115c8d45a/download
--------------------------------------------------
Nombre: 2022_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/5a74d097-6a31-421a-9493-3f67de18787c/download
--------------------------------------------------
Nombre: 2022_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/65490e4c-e33f-4320-9542-90058f0a6b37/download
--------------------------------------------------
Nombre: 2022_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/2e41fee1-5267-4ec7-9553-56dbe8a454e7/download
--------------------------------------------------
Nombre: 2022_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/6e3337af-b6c1-47b4-9deb-58d86802f00a/download
--------------------------------------------------
Nombre: 2022_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/23b53daa-5db1-434b-b68d-3f18981f1b90/download
--------------------------------------------------
Nombre: 2022_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/ed6e7971-79f4-422d-b0d9-8208369acb77/download
--------------------------------------------------
Nombre: 2021_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/081b0be9-246a-4f7a-bfc6-47682b27d88b/download
--------------------------------------------------
Nombre: 2021_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/d0fc5c39-8017-4812-b3ea-9c200a89b1b3/download
--------------------------------------------------
Nombre: 2021_03_Març_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/7fe6be55-75dd-4270-bcbf-a97f9a8dc0a3/download
--------------------------------------------------
Nombre: 2021_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e05e26c9-b8a2-4838-b673-61b85e30564e/download
--------------------------------------------------
Nombre: 2021_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/3cc4e750-bab8-48e4-9a96-3224153b36d7/download
--------------------------------------------------
Nombre: 2021_06_Juny_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/72e91d78-70bf-4949-9b24-3dc0fd238ae1/download
--------------------------------------------------
Nombre: 2021_07_Juliol_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/23cc51a0-382a-4b83-835b-b5f0da6614f0/download
--------------------------------------------------
Nombre: 2021_08_Agost_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/c100cd3f-72b9-4a73-a8c4-bbbe592d72a9/download
--------------------------------------------------
Nombre: 2021_09_Setembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/b5cf7ec2-334d-492c-84fa-23fbfa931d25/download
--------------------------------------------------
Nombre: 2021_10_Octubre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/e483b331-98cc-495d-85a9-8916419e3e6b/download
--------------------------------------------------
Nombre: 2021_11_Novembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/a87195e3-0819-43db-a43c-caa90327c68d/download
--------------------------------------------------
Nombre: 2021_12_Desembre_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1670e154-58dc-44e1-8138-8a167ef580ca/download
--------------------------------------------------
Nombre: 2020_01_Gener_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/138d7095-8d8e-4c0e-ac1a-9a280bf08083/download
--------------------------------------------------
Nombre: 2020_02_Febrer_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/71325945-95f0-4af5-ae01-ccf8be4781a1/download
--------------------------------------------------
Nombre: 2020_03_Marc_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/d229bf51-efe6-48b4-9192-40abda5caf19/download
--------------------------------------------------
Nombre: 2020_04_Abril_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/c5468d46-6cf4-4f1e-b7ad-d91292be830b/download
--------------------------------------------------
Nombre: 2020_05_Maig_BicingNou_ESTACIONS.7z
Formato: application/x-7z-compressed
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/6c03e39a-ca8f-451d-b8f3-c63cc56c23c4/download
--------------------------------------------------

Se ha utilizado el endpoint package_search para localizar un dataset relacionado con el servicio Bicing de Barcelona. Posteriormente, mediante package_show, se ha recuperado la información detallada del dataset, incluyendo su autor, organización responsable y los recursos disponibles para su descarga en diferentes formatos.

**3.2** De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

In [32]:
# Seleccionar el primer recurso en formato JSON
recurso = datos_show["result"]["resources"][0]

print(f"Nombre: {recurso['name']}")
print(f"Formato: {recurso['format']}")
print(f"URL: {recurso['url']}")

Nombre: Estat_Estacions_Bicing_securitzat_json
Formato: JSON
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/6aa3416d-ce1a-494d-861b-7bd07f069600/resource/1b215493-9e63-4a12-8980-2d7e0fa19f85/download

Del dataset **New Bicing stations status of Barcelona city** se ha seleccionado el recurso **Estat_Estacions_Bicing_securitzat_json**, ya que está disponible en formato **JSON**, lo que permite acceder a los datos fácilmente desde Python utilizando la librería requests.

**3.3** Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search por:

Recuperar al menos 100 registros.

In [ ]:
for recurso in datos_show["result"]["resources"]:  # Se necesita también el resource_id (en el JSON suele aparecer como id dentro de cada recurso).
    print(f"Nombre: {recurso['name']}")
    print(f"Resource ID: {recurso['id']}")
    print(f"Formato: {recurso['format']}")
    print("-" * 50)

Nombre: Estat_Estacions_Bicing_securitzat_json
Resource ID: 1b215493-9e63-4a12-8980-2d7e0fa19f85
Formato: JSON
--------------------------------------------------
Nombre: 2026_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: 28627d99-7c79-4eb5-bb30-2ef5016cf85e
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2026_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: 455a4db8-21ee-44e5-989b-12284e69cb86
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2026_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: aa833a84-e434-4139-a578-deffd73a592a
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2026_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: 6bfc88ee-66f0-4c1a-82d0-e8b268665536
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2026_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: e18c8a33-d81f-40e3-8929-09ee84c5e5ef
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: 6bfc06e2-ad96-4059-a57d-ce9334452c0f
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: af6f7cc4-3193-4b35-8e30-38f95df921cf
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: 0e904458-8d7a-42ac-b7c2-e41627a4577c
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: 885bbac5-a0d8-425e-919a-a4a855808785
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: c14e7b54-87c8-4ea8-aa1a-a8b5828989fe
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: 1b47f8e6-db40-4835-8d65-7f4349efb8f5
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: aba91b60-68f1-4a79-ba6b-c3ac87dc8c4e
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: 02d2975f-ce3c-4215-b1b2-eb6a2b4d019e
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: fb3e741b-299b-487d-98b4-11a8eb0634d1
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: efcfa487-708e-4766-aa2c-5d63451d11b2
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2025_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: fe880433-8468-4e85-a851-31036ab86af9
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: 229fdebf-daa8-4f22-9b0c-cf03ab0279ca
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: f482f76c-0aed-4c06-9abd-f90b3ea64d69
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: 869e5799-621d-497d-8364-1cb23b718da2
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: 03816585-7818-41ca-bc18-fdf56f839fb6
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: f8d0e63f-1c89-4bfc-bfe2-c180bdfbba70
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: e69daa68-0096-43e8-8e69-8219b9a13a4c
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: dc17e68c-6faf-4210-b93c-864e993e9d70
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: f0043c1f-38db-4e34-aaf8-8cd71174613b
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: 727dbd48-9348-4f43-a672-b79f73f1f8af
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: e5ed1e52-b205-49ff-b99c-a2307a8ce9a3
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: dec7d860-dcb9-46ac-b241-4d7e711c39d6
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2024_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: 29b46066-dc16-422d-85dd-6799baa7e839
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: 1ba8d8c4-c13b-47a8-b08f-19eba4266efc
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: 84c0d6e5-9011-40c2-80a7-65d9af4f671f
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: baba6358-6554-4629-877d-a82fd3925ed7
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: 5f8d4611-6125-4ce3-82fd-39c83f0e74bb
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: 829cce55-a081-48bf-9744-c61ea26073cc
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: f6bc68df-88a0-4e69-b513-dbbd941eea17
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: 4e75cb2a-7b6d-4f73-8ce6-be52de54d46c
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: e883bca2-d274-4eb5-8830-d75b080d34b3
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: 600f1b07-4af2-4fbb-b6d0-a473e3426d24
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: d41a1b34-503a-4e32-afc9-1850f74a2e3b
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: 813ab563-358b-4dd5-b41c-816bf3927763
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2023_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: 42e1d85c-86e3-4122-b1b3-de0f7fcf01fa
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: e13eda87-14c3-4589-9ff9-d721c3fa4dbb
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: 2e423344-cc5b-4c96-95e4-3f47bf29f089
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: f2b7e984-bb83-495d-b103-6e67631eb837
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: 72f96ab8-f8ae-46d8-8f4d-85220daff9fa
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: c35e536e-256d-4ab4-afe0-62e9034f5159
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: 697dbea2-eee2-4679-9dc4-100115c8d45a
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: 5a74d097-6a31-421a-9493-3f67de18787c
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: 65490e4c-e33f-4320-9542-90058f0a6b37
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: 2e41fee1-5267-4ec7-9553-56dbe8a454e7
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: 6e3337af-b6c1-47b4-9deb-58d86802f00a
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: 23b53daa-5db1-434b-b68d-3f18981f1b90
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2022_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: ed6e7971-79f4-422d-b0d9-8208369acb77
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: 081b0be9-246a-4f7a-bfc6-47682b27d88b
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: d0fc5c39-8017-4812-b3ea-9c200a89b1b3
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_03_Març_BicingNou_ESTACIONS.7z
Resource ID: 7fe6be55-75dd-4270-bcbf-a97f9a8dc0a3
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: e05e26c9-b8a2-4838-b673-61b85e30564e
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: 3cc4e750-bab8-48e4-9a96-3224153b36d7
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: 72e91d78-70bf-4949-9b24-3dc0fd238ae1
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: 23cc51a0-382a-4b83-835b-b5f0da6614f0
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: c100cd3f-72b9-4a73-a8c4-bbbe592d72a9
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: b5cf7ec2-334d-492c-84fa-23fbfa931d25
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: e483b331-98cc-495d-85a9-8916419e3e6b
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: a87195e3-0819-43db-a43c-caa90327c68d
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2021_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: 1670e154-58dc-44e1-8138-8a167ef580ca
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_01_Gener_BicingNou_ESTACIONS.7z
Resource ID: 138d7095-8d8e-4c0e-ac1a-9a280bf08083
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_02_Febrer_BicingNou_ESTACIONS.7z
Resource ID: 71325945-95f0-4af5-ae01-ccf8be4781a1
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: d229bf51-efe6-48b4-9192-40abda5caf19
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: c5468d46-6cf4-4f1e-b7ad-d91292be830b
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: 6c03e39a-ca8f-451d-b8f3-c63cc56c23c4
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: 16fbdedf-a150-4309-853d-f99cb2404a20
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: 9223b338-b8b3-427e-b1b4-b4dd14fd9586
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: 7970ad81-792b-45c6-888d-7f0e36f144b9
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: d9b34297-99b2-4cca-97c9-2ce7780289b4
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: 79aed163-0b24-498e-b8c0-a0ddbb0fb2b5
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: 3e9ba621-c2b0-4330-ae0d-092addc7afef
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2020_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: d33263e1-1be2-4ff1-98ef-395e8a56944a
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_03_Marc_BicingNou_ESTACIONS.7z
Resource ID: 6524ae13-bba4-4d83-b9d7-fbf679e64d10
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_04_Abril_BicingNou_ESTACIONS.7z
Resource ID: 428adbdd-96f4-4b21-acb1-caab41fbdff4
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_05_Maig_BicingNou_ESTACIONS.7z
Resource ID: 7d9400a5-fcd8-4b16-994e-9f117186fe87
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_06_Juny_BicingNou_ESTACIONS.7z
Resource ID: 6265796f-2cda-43c6-b34c-082c1af02397
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_07_Juliol_BicingNou_ESTACIONS.7z
Resource ID: bb374609-3e63-47a0-b821-0fd01f025eaa
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_08_Agost_BicingNou_ESTACIONS.7z
Resource ID: 7e234590-739d-4a13-be8c-90bc1be23ce1
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_09_Setembre_BicingNou_ESTACIONS.7z
Resource ID: 489d3e22-9cb4-42c9-812d-60c98d54324a
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_10_Octubre_BicingNou_ESTACIONS.7z
Resource ID: 743a5277-8f1f-4515-9de2-9f6ce20895b6
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_11_Novembre_BicingNou_ESTACIONS.7z
Resource ID: c6ad9c8c-c365-44bc-a420-1ee32f788251
Formato: application/x-7z-compressed
--------------------------------------------------
Nombre: 2019_12_Desembre_BicingNou_ESTACIONS.7z
Resource ID: 29ef34c6-1dde-49c8-a636-28a51ba647fe
Formato: application/x-7z-compressed
--------------------------------------------------

In [ ]:
url = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"  # Se utiliza un recurso compatible con DataStore para poder consultar los datos mediante el endpoint datastore_search.

parametros = {
    "resource_id": "dab3c7b7-ea76-4f00-b4a6-061c34363686",
    "limit": 100
}

respuesta = requests.get(url, params=parametros)

print(f"Código de estado: {respuesta.status_code}")

datos = respuesta.json()

print(f"Éxito: {datos['success']}")
print(f"Registros recuperados: {len(datos['result']['records'])}")

Código de estado: 200
Éxito: True
Registros recuperados: 100

3.4-  Convierte los resultados a un DataFrame.

In [39]:
# Convertir los registros obtenidos de la API en un DataFrame
df = pd.DataFrame(datos["result"]["records"])

# Mostrar las primeras filas
df.head()

  Codi_Districte  Sexe Nom_Districte    Edat Valor Escenari  _id   Any
0              1  Dona  Ciutat Vella  0 anys   394      Alt    1  2024
1              1  Dona  Ciutat Vella  0 anys   489      Alt    2  2025
2              1  Dona  Ciutat Vella  0 anys   516      Alt    3  2026
3              1  Dona  Ciutat Vella  0 anys   545      Alt    4  2027
4              1  Dona  Ciutat Vella  0 anys   574      Alt    5  2028

In [ ]:
3.5-  Guarda DataFrame en un archivo .csv.

In [40]:
# Guardar el DataFrame en un archivo CSV
df.to_csv("datos_opendata_bcn.csv", index=False)

print("Archivo 'datos_opendata_bcn.csv' guardado correctamente.")

Archivo 'datos_opendata_bcn.csv' guardado correctamente.